on:
  workflow_call:
    inputs:
      mergeMethod:
        required: false
        description: merge, squash, or rebase
        default: merge
        type: string
      maxVersionBump:
        required: false
        description: "['patch', 'minor', 'major'] maximum allowed version bump.  You probably don't want to automate major version bumps!"
        type: string
        default: "minor"
      skipCI:
        required: false
        description: Optionally skip ci builds on merges into main
        type: boolean
        default: false

jobs:
  dependabot-automerge:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm install -g @salesforce/plugin-release-management --omit=dev
      - name: run automerge command
        if: ${{ !inputs.skipCI }}
        env:
          GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN}}
        run: sf-release dependabot:automerge --merge-method ${{ inputs.mergeMethod}} --max-version-bump ${{ inputs.maxVersionBump}} --owner $GITHUB_REPOSITORY_OWNER --repo $(basename $GITHUB_REPOSITORY)
      - name: run automerge command
        if: ${{ inputs.skipCI }}
        env:
          GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN}}
        run: sf-release dependabot:automerge --merge-method ${{ inputs.mergeMethod}} --max-version-bump ${{ inputs.maxVersionBump}} --owner $GITHUB_REPOSITORY_OWNER --repo $(basename $GITHUB_REPOSITORY) --skip-ci
