on:
  workflow_call:
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN:
        description: A Github PAT with repo access.

jobs:
  publish:
    # todo: parameterize this as input if anyone ever needs ip-restricted runner
    runs-on: "ubuntu-latest"
    env:
      GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - name: Get Github user info
        id: github-user-info
        uses: salesforcecli/github-workflows/.github/actions/getGithubUserInfo@main
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main
        with:
          username: ${{ steps.github-user-info.outputs.username }}
          email: ${{ steps.github-user-info.outputs.email }}
      - name: build docs
        run: |
          rm -rf docs
          git worktree prune
          git fetch origin gh-pages:gh-pages
          git worktree add docs gh-pages
          yarn docs
      - name: send to git
        run: |
          cd docs
          git add .
          git commit -m 'docs: publishing gh-pages [skip ci]' --no-verify
          git push origin gh-pages --no-verify
